name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        version: 14.x
    - name: npm install, build
      run: |
        npm i
        npm i vsce -g
        node ./build/prepare-version.js
        node ./build/prepare.js
        cp -r temp/server /server
        vsce package
    - name: Upload
      uses: actions/upload-artifact@v2
      with: 
        name: VSCode-EmmyLuaCodeStyle
        path: ${{ github.workspace }}/emmylua-codestyle*.vsix